version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - packs:/app/public/packs
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
    ports:
      - 3000:3000
      - 54112:54112
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app_network

volumes:
  postgres_data:
  bundle:
  packs:
  node_modules:
  rails_cache:

networks:
  app_network:
