services:
  web:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - packs:/app/public/packs
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
    depends_on:
      - db
    networks:
      - app_network
    stdin_open: true
    tty: true
    command: bash
    ports:
      - 3000:3000
      - 54112:54112

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    networks:
      - app_network

volumes:
  postgres_data:
  bundle:
  packs:
  node_modules:
  rails_cache:

networks:
  app_network:
